/*
Customer Order Analysis
Dataset: WideWorldImporters

Goal:
Demonstrate how a simple business question evolves into deeper analysis
using joins, aggregation, filtering, and revenue calculations.

Each step represents a refinement of the original request.
*/


---------------------------------------------------------
-- Step 1
-- Business Request:
-- "I need a list of every Customer Name and the Invoice Date
-- for every purchase they have made."
--
-- Purpose:
-- This establishes the base relationship between customers
-- and invoices. Each row represents a purchase event.
---------------------------------------------------------

SELECT sc.CustomerName, si.InvoiceDate
FROM Sales.Customers sc
JOIN Sales.Invoices si
	ON sc.CustomerID = si.CustomerID



---------------------------------------------------------
-- Step 2
-- Business Request:
-- "I need a list of our customers and how many total orders
-- each one has placed. Put the customers with the most
-- orders at the top."
--
-- Purpose:
-- Move from transactional data to summarized insights by
-- counting invoices per customer.
---------------------------------------------------------

SELECT sc.CustomerName, COUNT(si.InvoiceID) AS TotalOrders
FROM Sales.Customers sc
JOIN Sales.Invoices si
	ON sc.CustomerID = si.CustomerID
GROUP BY sc.CustomerName
ORDER BY TotalOrders DESC



---------------------------------------------------------
-- Step 3
-- Business Request:
-- "I need the same list (Customer Name and Total Order Count),
-- but I only want to see customers who have placed more
-- than 10 orders."
--
-- Purpose:
-- Apply a HAVING clause to filter grouped results,
-- focusing on high-frequency customers.
---------------------------------------------------------

SELECT sc.CustomerName, COUNT(si.InvoiceID) AS TotalOrders
FROM Sales.Customers sc
JOIN Sales.Invoices si
	ON sc.CustomerID = si.CustomerID
GROUP BY sc.CustomerName
HAVING COUNT(si.InvoiceID) > 10
ORDER BY TotalOrders DESC



---------------------------------------------------------
-- Step 4
-- Business Request:
-- "The count of orders is great, but some orders are for
-- $10 and some are for $10,000. I need to see the Total
-- Transaction Amount for each of these customers alongside
-- their order count."
--
-- Purpose:
-- Extend the analysis by incorporating financial data.
-- This joins transaction tables to calculate total
-- revenue generated by each customer.
--
-- Additional filtering:
-- Focus only on transactions tied to orders in 2016.
---------------------------------------------------------

SELECT sc.CustomerName, 
FORMAT(COUNT(si.InvoiceID), 'N0') AS TotalOrders, 
FORMAT(SUM(ct.TransactionAmount), 'C') AS TotalSpent
FROM Sales.Customers sc
JOIN Sales.Invoices si
	ON sc.CustomerID = si.CustomerID
JOIN Sales.CustomerTransactions ct
	ON sc.CustomerID = ct.CustomerID
JOIN SALES.Orders so
	ON ct.CustomerID = so.CustomerID
WHERE so.OrderDate >= '2016-01-01' AND so.OrderDate <= '2016-12-31'
GROUP BY sc.CustomerName
HAVING COUNT(si.InvoiceID) > 10 
ORDER BY SUM(ct.TransactionAmount) DESC
